name: Jack_Scheduled_Scan
on:
  schedule:
    - cron: '00 04 * * *' # 日本時間 13:00
    - cron: '00 07 * * *' # 日本時間 16:00
  workflow_dispatch:      # 手動実行ボタンを表示

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas google-genai discord-webhook numpy streamlit

      - name: Run Scan
        run: python main.py
