name: Jack_Scheduled_Scan
on:
  schedule:
    - cron: '00 04 * * *' # 日本時間 13:00
    - cron: '00 07 * * *' # 日本時間 16:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 安定性のために3.10を指定します
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # pandas-taが動く安定したバージョンを指定
          pip install "pandas<2.1.0" "numpy<2.0.0"
          pip install yfinance google-generativeai discord-webhook pandas-ta
      - name: Run Scan
        run: python main.py
